Metrics/MethodLength:
  Max: 25
Metrics/AbcSize:
  Enabled: false
Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
AllCops:
  NewCops: enable
  Exclude:
    - spec/**
  SuggestExtensions: false
