Metrics/MethodLength:
  Max: 50
Metrics/ClassLength:
  Max: 200
Metrics/ParameterLists:
  Max: 7
  MaxOptionalParameters: 7
Style/OptionalBooleanParameter:
  Enabled: false
Layout/LineLength:
  Max: 150
Metrics/AbcSize:
  Enabled: false
Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.3
  Exclude:
    - 'spec/**/*'
  SuggestExtensions: false
