---
Name: "Constant Input Example"
Graph:
  - Name: "myinput"
    Type: "input"
    Class: "DAF::ConstantInput"
    Options:
      constant: "Hello from constant input!"
  - Name: "myaction"
    Type: "action"
    Class: "DAF::ShellAction"
    Options:
      command: "echo 'Received: {{output}}'"
---