---
Monitor:
  Type: GithubRepositoryMonitor
  Options: 
    owner: klmcarthur
    branch: master
    repository: DAF 
    frequency: 10

Action:
  Type: EmailAction
  Options:
    to: test@example.com
    from: test@example.com
    subject: Test Email
    body: test email body
---
