---
Monitor:
  Type: FileUpdateMonitor
  Options: 
    path: /tmp/test1
    frequency: 2

Action:
  Type: EmailAction
  Options:
    to: test@example.com
    from: test@example.com
    subject: "{{contents}}"
    body: test email body again
---
